title: Research Cluster Tutorial
description: Research Computing cluster documentation
theme: just-the-docs

url: https://fandm-college.github.io
baseurl: cluster

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/globus.png"

#aux_links:
#  RCS home: https://github.com/just-the-docs/just-the-docs-template

# Callout configuration
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red